### ISSUE TITLE
2 CSV formatting issues

### ISSUE THREAD

**Issue by jalbrecht** [jamesgordo/php-csv-parser#1]
Hey there. I used this to parse some CSV's and it made it super easy. 2 problems I ran into:

1. The CSV line length is set to 1,000 (https://github.com/jamesgordo/php-csv-parser/blob/master/src/Parser.php#L140). My CSV was unusually large in columns so it was cutting them off which caused a lot of parsing issues.  PHP 5.1.0 and later you can set it to 0 which allows unlimited length
2. Trimming the header titles. I had two issues here. One was blank space and one was a zero width no-break space character causing issues. Visually the dump looked fine ($Data->ABN) but really it was $Data->&#65729;ABN which I only found when var_dumping it and inspecting it with the Chrome dev tools (preg_replace fix here: https://stackoverflow.com/questions/6538203/how-to-avoid-echoing-character-65279-in-php-this-question-also-relates-to-java)

I was using the Australian registered charity dataset (10mb, might want to use the first few lines): http://data.gov.au/dataset/b050b242-4487-4306-abf5-07ca073e5594/resource/eb1e6be4-5b13-4feb-b28e-388bf7c26f93/download/20170731datadotgovmain.zip

**Comment by jamesgordo** [comment]
Hi @jalbrecht . Thank you so much for addressing these issues. This has been implemented on my latest release. Please let me know how it goes.
