### ISSUE TITLE
First Column empty Issue

### ISSUE THREAD

**Issue by perlatsp** [jamesgordo/php-csv-parser#7]
This line can cause issues if you have a CSV file that happens to have an empty value for the first column. 
ignoring the whole CSV file.
example this CSV file exported from excel.:

```
age,name,surname
,james,smith
,george,adams
```
```php
$file = new Parser( $url );
var_dump( $file->all() ) // this will be an empty array
```

https://github.com/jamesgordo/php-csv-parser/blob/4021b82cf628b36dc7dfe0054f85f4ec0d8d96b8/src/Parser.php#LL181C17-L181C17

**Comment by jamesgordo** [comment]
Hi @perlatsp . Thank you for submitting this issue. I released a fix for this one [PR](https://github.com/jamesgordo/php-csv-parser/pull/8). Kindly update your version to `1.0.5`.
